apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ratelimit
data:
  config.yaml: |
    domain: oauth-ratelimit
    descriptors:
      - key: PATH
        value: "/oauth/v1/health"
        descriptors:
          - key: TENANTID
            value: tenant01
            rate_limit:
              unit: minute
              requests_per_unit: 5
          - key: TENANTID
            value: tenant02
            rate_limit:
              unit: minute
              requests_per_unit: 8
          - key: TENANTID
            rate_limit:
              unit: minute
              requests_per_unit: 3
#      - key: PATH
#        rate_limit:
#          unit: minute
#          requests_per_unit: 1000
